from datetime import datetime
import asyncio
from .db import get_conn
from .state_machine import set_state
from .audit import write_audit
from .idempotency import reserve
from .github_service import create_repo, create_branch, push_files, create_pr, list_reviews
from .vercel_service import create_project, set_env, create_deployment, get_deployment

def save_run(job_id, stage, content):
    with get_conn() as conn:
        conn.execute('INSERT INTO job_runs (job_id, stage, content, created_at) VALUES (%s,%s,%s,%s)', (job_id, stage, str(content), datetime.utcnow().isoformat()))

def update_job(job_id, **fields):
    if not fields: return
    cols = ', '.join([f"{k} = %s" for k in fields.keys()]) + ', updated_at = %s'
    values = list(fields.values()) + [datetime.utcnow().isoformat(), job_id]
    with get_conn() as conn:
        conn.execute(f'UPDATE jobs SET {cols} WHERE id = %s', values)

async def run_async(job_id):
    with get_conn() as conn:
        job = conn.execute('SELECT * FROM jobs WHERE id = %s', (job_id,)).fetchone()
    if not job:
        return {'error': 'job not found'}
    app_name = job['app_name']
    repo_name = job['repo_name']
    branch_name = job['branch_name']
    files = [
        {'path': 'README.md', 'content': f'# {app_name}\n\nGenerated by Forge Agent v17.'},
        {'path': 'app/page.tsx', 'content': f'export default function Page() {{ return <main><h1>{app_name}</h1></main> }}'}
    ]
    set_state(job_id, 'generated', 'Prepared app files')
    save_run(job_id, 'files_prepared', files)

    if reserve(job_id, 'publish', f'{job_id}:publish'):
        set_state(job_id, 'publishing', 'Publishing to GitHub')
        repo = await create_repo(repo_name)
        save_run(job_id, 'github_repo', repo)
        branch = await create_branch(repo_name, branch_name)
        save_run(job_id, 'github_branch', branch)
        pushed = await push_files(repo_name, branch_name, files)
        save_run(job_id, 'github_push', pushed)
        pr = await create_pr(repo_name, branch_name, branch.get('base_branch', 'main'), f'Forge build for {app_name}', f'Automated PR for job {job_id}')
        save_run(job_id, 'github_pr', pr)
        pr_url = (pr.get('data') or {}).get('html_url') if isinstance(pr, dict) else None
        update_job(job_id, pr_url=pr_url)
        pull_number = (pr.get('data') or {}).get('number') if isinstance(pr, dict) else None
        if pull_number:
            reviews = await list_reviews(repo_name, pull_number)
            save_run(job_id, 'github_reviews', reviews)

    if reserve(job_id, 'deploy', f'{job_id}:deploy'):
        set_state(job_id, 'deploying', 'Deploying to Vercel')
        project = await create_project(repo_name, repo=f"{__import__('os').getenv('GITHUB_OWNER','')}/{repo_name}")
        save_run(job_id, 'vercel_project', project)
        env_result = await set_env(repo_name, 'EXAMPLE_KEY', 'example-value', target='preview')
        save_run(job_id, 'vercel_env', env_result)
        deployment = await create_deployment(repo_name, repo=f"{__import__('os').getenv('GITHUB_OWNER','')}/{repo_name}")
        save_run(job_id, 'vercel_deployment', deployment)
        dep = deployment.get('data', {}) if isinstance(deployment, dict) else {}
        dep_id = dep.get('id')
        dep_url = dep.get('url')
        dep_state = None
        if dep_id:
            dep_status = await get_deployment(dep_id)
            save_run(job_id, 'vercel_deployment_status', dep_status)
            dep_state = (dep_status.get('data') or {}).get('readyState') if isinstance(dep_status, dict) else None
        update_job(job_id, deployment_id=dep_id, deployment_url=dep_url, deployment_state=dep_state or 'UNKNOWN', status='complete')

    set_state(job_id, 'complete', 'Pipeline complete')
    write_audit(job_id, 'pipeline_complete', {'job_id': job_id})
    return {'ok': True, 'job_id': job_id}

def run_pipeline(job_id):
    return asyncio.run(run_async(job_id))
