import logging
import asyncio
from datetime import datetime, timezone
from .db import get_conn
from .state_machine import set_state
from .audit import write_audit
from .idempotency import reserve
from .github_service import create_repo, create_branch, push_files, create_pr, list_reviews
from .vercel_service import create_project, set_env, create_deployment, get_deployment

logger = logging.getLogger("forge_agent.pipeline")


def save_run(job_id: str, stage: str, content):
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO job_runs (job_id, stage, content, created_at) VALUES (%s,%s,%s,%s)",
            (job_id, stage, str(content), datetime.now(timezone.utc).isoformat()),
        )


def update_job(job_id: str, **fields):
    """Update job fields using parameterized queries (no f-string SQL injection)."""
    if not fields:
        return
    allowed_columns = {
        "status", "repo_name", "branch_name", "pr_url",
        "deployment_id", "deployment_url", "deployment_state", "repair_attempts",
    }
    for key in fields:
        if key not in allowed_columns:
            raise ValueError(f"Disallowed column: {key}")

    set_clauses = [f"{k} = %s" for k in fields]
    set_clauses.append("updated_at = %s")
    values = list(fields.values()) + [datetime.now(timezone.utc).isoformat(), job_id]

    with get_conn() as conn:
        conn.execute(
            f"UPDATE jobs SET {', '.join(set_clauses)} WHERE id = %s", values
        )


async def _publish_to_github(job_id: str, job: dict, files: list) -> str | None:
    """Publish code to GitHub. Returns PR URL or None."""
    import os
    repo_name = job["repo_name"]
    branch_name = job["branch_name"]

    set_state(job_id, "publishing", "Publishing to GitHub")

    repo = await create_repo(repo_name)
    save_run(job_id, "github_repo", repo)
    if repo["status_code"] not in (201, 422):  # 422 = already exists
        logger.error("Failed to create repo: %s", repo)
        raise RuntimeError(f"GitHub repo creation failed: {repo['status_code']}")

    branch = await create_branch(repo_name, branch_name)
    save_run(job_id, "github_branch", branch)

    pushed = await push_files(repo_name, branch_name, files)
    save_run(job_id, "github_push", pushed)

    base_branch = branch.get("base_branch", "main")
    pr = await create_pr(
        repo_name, branch_name, base_branch,
        f"Forge build for {job['app_name']}",
        f"Automated PR for job {job_id}",
    )
    save_run(job_id, "github_pr", pr)

    pr_url = None
    if isinstance(pr, dict) and pr.get("data"):
        pr_url = pr["data"].get("html_url")
        pull_number = pr["data"].get("number")
        if pull_number:
            reviews = await list_reviews(repo_name, pull_number)
            save_run(job_id, "github_reviews", reviews)

    update_job(job_id, pr_url=pr_url)
    return pr_url


async def _deploy_to_vercel(job_id: str, job: dict) -> dict:
    """Deploy to Vercel. Returns deployment info."""
    import os
    repo_name = job["repo_name"]
    owner = os.getenv("GITHUB_OWNER", "")

    set_state(job_id, "deploying", "Deploying to Vercel")

    project = await create_project(repo_name, repo=f"{owner}/{repo_name}")
    save_run(job_id, "vercel_project", project)

    env_result = await set_env(repo_name, "EXAMPLE_KEY", "example-value", target="preview")
    save_run(job_id, "vercel_env", env_result)

    deployment = await create_deployment(repo_name, repo=f"{owner}/{repo_name}")
    save_run(job_id, "vercel_deployment", deployment)

    dep = deployment.get("data", {}) if isinstance(deployment, dict) else {}
    dep_id = dep.get("id")
    dep_url = dep.get("url")
    dep_state = None

    if dep_id:
        dep_status = await get_deployment(dep_id)
        save_run(job_id, "vercel_deployment_status", dep_status)
        dep_state = (dep_status.get("data") or {}).get("readyState") if isinstance(dep_status, dict) else None

    update_job(
        job_id,
        deployment_id=dep_id or "",
        deployment_url=dep_url or "",
        deployment_state=dep_state or "UNKNOWN",
    )
    return {"dep_id": dep_id, "dep_url": dep_url, "dep_state": dep_state}


async def run_async(job_id: str):
    """Main async pipeline orchestrator."""
    logger.info("Pipeline starting for job %s", job_id)

    with get_conn() as conn:
        job = conn.execute("SELECT * FROM jobs WHERE id = %s", (job_id,)).fetchone()
    if not job:
        logger.error("Job %s not found", job_id)
        return {"error": "job not found"}

    job = dict(job)

    try:
        # Stage 1: Generate files
        files = [
            {"path": "README.md", "content": f"# {job['app_name']}\n\nGenerated by Forge Agent."},
            {"path": "app/page.tsx", "content": f"export default function Page() {{ return <main><h1>{job['app_name']}</h1></main> }}"},
        ]
        set_state(job_id, "generated", "Prepared app files")
        save_run(job_id, "files_prepared", files)

        # Stage 2: Publish to GitHub
        if reserve(job_id, "publish", f"{job_id}:publish"):
            await _publish_to_github(job_id, job, files)

        # Stage 3: Deploy to Vercel
        if reserve(job_id, "deploy", f"{job_id}:deploy"):
            await _deploy_to_vercel(job_id, job)

        # Done
        update_job(job_id, status="complete")
        set_state(job_id, "complete", "Pipeline complete")
        write_audit(job_id, "pipeline_complete", {"job_id": job_id})
        logger.info("Pipeline completed for job %s", job_id)
        return {"ok": True, "job_id": job_id}

    except Exception as e:
        logger.exception("Pipeline failed for job %s", job_id)
        set_state(job_id, "failed", str(e))
        update_job(job_id, status="failed")
        write_audit(job_id, "pipeline_failed", {"job_id": job_id, "error": str(e)})
        raise


def run_pipeline(job_id: str):
    """Sync entry point for Celery — runs the async pipeline."""
    return asyncio.run(run_async(job_id))
