import logging
import asyncio
import json
from datetime import datetime, timezone
from .db import get_conn
from .state_machine import set_state
from .audit import write_audit
from .idempotency import reserve
from .github_service import create_repo, create_branch, push_files, create_pr, list_reviews
from .cloudflare_service import create_pages_project, set_env_vars, create_deployment, get_deployment
from .provider_router import generate_text

logger = logging.getLogger("forge_agent.pipeline")


def save_run(job_id: str, stage: str, content):
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO job_runs (job_id, stage, content, created_at) VALUES (%s,%s,%s,%s)",
            (job_id, stage, str(content), datetime.now(timezone.utc).isoformat()),
        )


def update_job(job_id: str, **fields):
    """Update job fields using parameterized queries."""
    if not fields:
        return
    allowed_columns = {
        "status", "repo_name", "branch_name", "pr_url",
        "deployment_id", "deployment_url", "deployment_state", "repair_attempts",
    }
    for key in fields:
        if key not in allowed_columns:
            raise ValueError(f"Disallowed column: {key}")
    set_clauses = [f"{k} = %s" for k in fields]
    set_clauses.append("updated_at = %s")
    values = list(fields.values()) + [datetime.now(timezone.utc).isoformat(), job_id]
    with get_conn() as conn:
        conn.execute(f"UPDATE jobs SET {', '.join(set_clauses)} WHERE id = %s", values)


async def _generate_files(job_id: str, job: dict) -> list:
    """Generate application files using the AI provider.
    
    Model selection:
    - If job has explicit model override, use that
    - Otherwise, use free model (default) for initial generation
    """
    app_name = job["app_name"]
    prompt = job["prompt"]
    model_override = job.get("model")  # From frontend model selector

    system_prompt = f"""You are a code generation assistant. Generate a complete Next.js application.
App name: {app_name}
Return ONLY valid JSON: [{{"path": "filename", "content": "file content"}}]"""

    try:
        result = await generate_text(
            provider=job.get("provider", "opencode-go"),
            system_prompt=system_prompt,
            user_prompt=prompt,
            model_override=model_override,
        )
        # Try to parse AI output as file list
        if result.strip().startswith("["):
            files = json.loads(result)
            if isinstance(files, list) and all("path" in f and "content" in f for f in files):
                save_run(job_id, "ai_generation", {"model": model_override or "auto", "file_count": len(files)})
                return files
    except Exception as e:
        logger.warning("AI generation failed, using template: %s", e)
        save_run(job_id, "ai_generation_error", str(e))

    # Fallback to template files
    return [
        {"path": "README.md", "content": f"# {app_name}\n\nGenerated by Forge Agent."},
        {"path": "app/page.tsx", "content": f'export default function Page() {{ return <main><h1>{app_name}</h1></main> }}'},
        {"path": "package.json", "content": json.dumps({
            "name": app_name.lower().replace(" ", "-"), "version": "0.1.0", "private": True,
            "scripts": {"dev": "next dev", "build": "next build", "start": "next start"},
            "dependencies": {"next": "^15.0.0", "react": "^19.0.0", "react-dom": "^19.0.0"},
        }, indent=2)},
        {"path": "next.config.ts", "content": "import type { NextConfig } from 'next';\nconst config: NextConfig = { output: 'export' };\nexport default config;"},
    ]


async def _publish_to_github(job_id: str, job: dict, files: list) -> str | None:
    """Publish code to GitHub. Returns PR URL or None."""
    repo_name = job["repo_name"]
    branch_name = job["branch_name"]

    set_state(job_id, "publishing", "Publishing to GitHub")

    repo = await create_repo(repo_name)
    save_run(job_id, "github_repo", repo)
    if repo["status_code"] not in (201, 422):
        logger.error("Failed to create repo: %s", repo)
        raise RuntimeError(f"GitHub repo creation failed: {repo['status_code']}")

    branch = await create_branch(repo_name, branch_name)
    save_run(job_id, "github_branch", branch)

    push_branch = branch_name
    if isinstance(branch.get("data"), dict) and branch["data"].get("skipped"):
        push_branch = branch.get("base_branch", "main")
        logger.info("Using base branch %s for push (new empty repo)", push_branch)

    pushed = await push_files(repo_name, push_branch, files)
    save_run(job_id, "github_push", pushed)

    pr_url = None
    if push_branch == branch_name:
        base_branch = branch.get("base_branch", "main")
        pr = await create_pr(
            repo_name, branch_name, base_branch,
            f"Forge build for {job['app_name']}",
            f"Automated PR for job {job_id}",
        )
        save_run(job_id, "github_pr", pr)
        if isinstance(pr, dict) and pr.get("data"):
            pr_url = pr["data"].get("html_url")
            pull_number = pr["data"].get("number")
            if pull_number:
                reviews = await list_reviews(repo_name, pull_number)
                save_run(job_id, "github_reviews", reviews)

    update_job(job_id, pr_url=pr_url or "")
    return pr_url


async def _deploy_to_cloudflare(job_id: str, job: dict, files: list) -> dict:
    """Deploy to Cloudflare Pages via direct upload."""
    repo_name = job["repo_name"]
    set_state(job_id, "deploying", "Deploying to Cloudflare Pages")

    project = await create_pages_project(repo_name)
    save_run(job_id, "cloudflare_project", project)

    deploy_files = _build_static_files(job, files)
    deployment = await create_deployment(repo_name, files=deploy_files)
    save_run(job_id, "cloudflare_deployment", deployment)

    dep = deployment.get("data", {}) if isinstance(deployment, dict) else {}
    result_data = dep.get("result", {}) if isinstance(dep, dict) else {}
    dep_id = result_data.get("id") or dep.get("id")
    dep_url = result_data.get("url") or dep.get("url")
    dep_state = None

    if dep_id:
        dep_status = await get_deployment(repo_name, dep_id)
        save_run(job_id, "cloudflare_deployment_status", dep_status)
        status_data = dep_status.get("data", {}) if isinstance(dep_status, dict) else {}
        status_result = status_data.get("result", {}) if isinstance(status_data, dict) else {}
        dep_state = status_result.get("latest_stage", {}).get("name") if isinstance(status_result, dict) else None

    update_job(
        job_id,
        deployment_id=dep_id or "",
        deployment_url=dep_url or "",
        deployment_state=dep_state or "UNKNOWN",
    )
    return {"dep_id": dep_id, "dep_url": dep_url, "dep_state": dep_state}


def _build_static_files(job: dict, source_files: list) -> list:
    """Convert source files into static HTML for Cloudflare Pages deployment."""
    app_name = job.get("app_name", "App")
    return [{
        "path": "index.html",
        "content": f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{app_name}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>body{{font-family:system-ui;max-width:800px;margin:2rem auto;padding:0 1rem}}</style>
</head><body><h1>{app_name}</h1><p>Generated by Forge Agent</p></body></html>""",
    }]


async def run_async(job_id: str):
    """Main async pipeline orchestrator."""
    logger.info("Pipeline starting for job %s", job_id)

    with get_conn() as conn:
        job = conn.execute("SELECT * FROM jobs WHERE id = %s", (job_id,)).fetchone()
    if not job:
        logger.error("Job %s not found", job_id)
        return {"error": "job not found"}

    job = dict(job)

    try:
        set_state(job_id, "generated", "Generating app files")
        files = await _generate_files(job_id, job)
        save_run(job_id, "files_prepared", [{"path": f["path"]} for f in files])

        if reserve(job_id, "publish", f"{job_id}:publish"):
            await _publish_to_github(job_id, job, files)

        if reserve(job_id, "deploy", f"{job_id}:deploy"):
            await _deploy_to_cloudflare(job_id, job, files)

        update_job(job_id, status="complete")
        set_state(job_id, "complete", "Pipeline complete")
        write_audit(job_id, "pipeline_complete", {"job_id": job_id})
        logger.info("Pipeline completed for job %s", job_id)
        return {"ok": True, "job_id": job_id}

    except Exception as e:
        logger.exception("Pipeline failed for job %s", job_id)
        set_state(job_id, "failed", str(e))
        update_job(job_id, status="failed")
        write_audit(job_id, "pipeline_failed", {"job_id": job_id, "error": str(e)})
        raise


def run_pipeline(job_id: str):
    """Sync entry point for Celery."""
    return asyncio.run(run_async(job_id))
